package migrations

import (
	"log"

	"github.com/jmoiron/sqlx"
	"github.com/knadh/koanf/v2"
	"github.com/knadh/stuffbin"
)

// V6_42_0 renames the "organization secondary list" concept to "organization
// pool allocation" (org_pool_allocation) end to end: the customer_list_type
// label, the pool_segment* tables, every column that references them, the
// explicitly named indexes, and the values earlier releases already persisted
// (audit actions/object types and the exclusion source marker).
//
// Every statement is guarded, so the migration is idempotent and a no-op on
// databases created from the current schema.sql, which already ships the new
// names. The historical migrations keep the old names on purpose: they run
// before this one and must still see the old shape.
func V6_42_0(db *sqlx.DB, _ stuffbin.FileSystem, _ *koanf.Koanf, _ *log.Logger) error {
	_, err := db.Exec(`
		DO $$ BEGIN
			-- RENAME VALUE rewrites the label in place. Existing customer_lists.type
			-- rows follow automatically because PostgreSQL stores the label's OID.
			-- The check resolves the type through the search path instead of matching
			-- every type with that name, so an unrelated schema cannot satisfy it.
			IF to_regtype('customer_list_type') IS NOT NULL
				AND EXISTS (SELECT 1 FROM pg_enum WHERE enumtypid=to_regtype('customer_list_type') AND enumlabel='pool_segment')
				AND NOT EXISTS (SELECT 1 FROM pg_enum WHERE enumtypid=to_regtype('customer_list_type') AND enumlabel='org_pool_allocation') THEN
				ALTER TYPE customer_list_type RENAME VALUE 'pool_segment' TO 'org_pool_allocation';
			END IF;
		END $$;

		DO $$ BEGIN
			IF to_regclass('pool_segments') IS NOT NULL AND to_regclass('org_pool_allocations') IS NULL THEN ALTER TABLE pool_segments RENAME TO org_pool_allocations; END IF;
			IF to_regclass('pool_segment_members') IS NOT NULL AND to_regclass('org_pool_allocation_members') IS NULL THEN ALTER TABLE pool_segment_members RENAME TO org_pool_allocation_members; END IF;
			IF to_regclass('pool_segment_exclusions') IS NOT NULL AND to_regclass('org_pool_allocation_exclusions') IS NULL THEN ALTER TABLE pool_segment_exclusions RENAME TO org_pool_allocation_exclusions; END IF;
		END $$;

		DO $$ BEGIN
			-- Resolve the columns the same way the DDL below does, through the search
			-- path, so a search path whose first schema is not the schema holding
			-- these tables cannot silently skip the renames.
			IF EXISTS (SELECT 1 FROM pg_attribute a WHERE a.attrelid=to_regclass('org_pool_allocation_members') AND a.attname='segment_id' AND NOT a.attisdropped) THEN ALTER TABLE org_pool_allocation_members RENAME COLUMN segment_id TO allocation_id; END IF;
			IF EXISTS (SELECT 1 FROM pg_attribute a WHERE a.attrelid=to_regclass('org_pool_allocation_exclusions') AND a.attname='segment_id' AND NOT a.attisdropped) THEN ALTER TABLE org_pool_allocation_exclusions RENAME COLUMN segment_id TO allocation_id; END IF;
			IF EXISTS (SELECT 1 FROM pg_attribute a WHERE a.attrelid=to_regclass('campaign_customer_lists') AND a.attname='pool_segment_id' AND NOT a.attisdropped) THEN ALTER TABLE campaign_customer_lists RENAME COLUMN pool_segment_id TO org_pool_allocation_id; END IF;
			IF EXISTS (SELECT 1 FROM pg_attribute a WHERE a.attrelid=to_regclass('campaign_recipients') AND a.attname='source_segment_id' AND NOT a.attisdropped) THEN ALTER TABLE campaign_recipients RENAME COLUMN source_segment_id TO source_allocation_id; END IF;
			IF EXISTS (SELECT 1 FROM pg_attribute a WHERE a.attrelid=to_regclass('campaign_pool_recipients') AND a.attname='segment_id' AND NOT a.attisdropped) THEN ALTER TABLE campaign_pool_recipients RENAME COLUMN segment_id TO allocation_id; END IF;
			IF EXISTS (SELECT 1 FROM pg_attribute a WHERE a.attrelid=to_regclass('bounces') AND a.attname='source_segment_id' AND NOT a.attisdropped) THEN ALTER TABLE bounces RENAME COLUMN source_segment_id TO source_allocation_id; END IF;
			IF EXISTS (SELECT 1 FROM pg_attribute a WHERE a.attrelid=to_regclass('reply_ai_events') AND a.attname='source_segment_id' AND NOT a.attisdropped) THEN ALTER TABLE reply_ai_events RENAME COLUMN source_segment_id TO source_allocation_id; END IF;
		END $$;

		-- Only the indexes that are created by name are renamed. Indexes whose names
		-- never mentioned the old concept (idx_campaign_customer_lists_pool and
		-- friends) keep their names; PostgreSQL rewrites their definitions when the
		-- underlying columns are renamed. Constraint names generated by PostgreSQL
		-- (for example pool_segments_pkey) also keep their historical names, which
		-- matches how earlier rename migrations in this package behaved.
		-- idx_org_pool_allocations_org and idx_org_pool_allocation_members_status only
		-- ever existed on upgraded databases: schema.sql does not create them. Their
		-- (renamed) definitions are therefore left in place instead of dropping them
		-- or adding them to schema.sql, which would change the shape of one of the
		-- two install paths beyond this rename.
		DO $$ BEGIN
			IF to_regclass('idx_pool_segments_pool_org') IS NOT NULL AND to_regclass('idx_org_pool_allocations_pool_org') IS NULL THEN ALTER INDEX idx_pool_segments_pool_org RENAME TO idx_org_pool_allocations_pool_org; END IF;
			IF to_regclass('idx_pool_segments_org') IS NOT NULL AND to_regclass('idx_org_pool_allocations_org') IS NULL THEN ALTER INDEX idx_pool_segments_org RENAME TO idx_org_pool_allocations_org; END IF;
			IF to_regclass('idx_pool_segment_members_status') IS NOT NULL AND to_regclass('idx_org_pool_allocation_members_status') IS NULL THEN ALTER INDEX idx_pool_segment_members_status RENAME TO idx_org_pool_allocation_members_status; END IF;
		END $$;

		DO $$ BEGIN
			IF to_regclass('org_pool_allocation_exclusions') IS NOT NULL THEN
				UPDATE org_pool_allocation_exclusions SET source='allocation' WHERE source='segment';
				-- schema.sql ships DEFAULT 'allocation'; the pre-rename table defaulted
				-- to 'segment', so upgraded databases are normalized explicitly.
				ALTER TABLE org_pool_allocation_exclusions ALTER COLUMN source SET DEFAULT 'allocation';
			END IF;
			IF to_regclass('audit_events') IS NOT NULL THEN
				-- Earlier releases wrote the old name into the audit trail. Rewriting
				-- the persisted values keeps existing audit rows resolving to the
				-- renamed object instead of showing a stale identifier to operators.
				UPDATE audit_events SET action=REPLACE(action,'pool_segment','org_pool_allocation') WHERE action LIKE 'pool_segment.%';
				UPDATE audit_events SET object_type='org_pool_allocation' WHERE object_type='pool_segment';
			END IF;
		END $$;
	`)
	return err
}
